### ISSUE TITLE
Option to add a short message to a payment

### ISSUE THREAD

**Issue by athloni** [appditto/natrium_wallet_flutter#44] opened 2019-06-26 14:47 UTC
It would be nice if there would be an option to add a short message (reference) to an transaction (Natrium to Natrium). Like "Thanks for the nice diner". 
That way the receiver knows why he received the payment.

**Comment by bbedward** [comment] 2019-06-26 14:50
Duplicate of #7 

We're somewhat limited on the length of messages, if we go the on-chain route, since nano doesnt have any data fields on blocks. But it's definitely achievable

**Closed by bbedward** 2019-06-26 14:50 UTC

**Comment by athloni** [comment] 2019-06-28 07:51
Great man!!!!

**Comment by athloni** [comment] 2019-06-28 07:53
But I prefer to do it OFF chain because of privacy. So Natrium to Natrium only. Other wallets cab adopt it I they wan't to.
