### ISSUE TITLE
Wallet is destroyed when following deep link

### ISSUE THREAD

**Issue by alecrios** [appditto/natrium_wallet_flutter#110] opened 2021-02-07 18:33 UTC
When following a Nano deep link from a browser, Natrium goes black and freezes. Upon restart, the existing wallet is gone and Natrium shows the initial onboarding screen. Can't repro consistently, but I've now had it happen several times.

Platform: iOS v14.4
App Version: v2.3.5
Example link: `nano:nano_3x4ui45q1cw8hydmfdn4ec5ijsdqi4ryp14g4ayh71jcdkwmddrq7ca9xzn9?amount=1000000000000000000000000000000`

**Comment by aufbakanleitung** [comment] 2021-02-09 17:41
This sound really scary. Do you mean the contents of the wallet are no longer accessible?

**Comment by alecrios** [comment] 2021-02-10 04:41
@aufbakanleitung That's right. The app seems to reset to its initial state.

**Comment by alecrios** [comment] 2021-02-10 04:45
@bbedward Just tagging you here to make sure you see this, as I'd consider it high priority.

**Comment by bbedward** [comment] 2021-02-10 13:16
I'll try to reproduce on my iOS devices and see if I can reproduce - which device are you using?

**Comment by alecrios** [comment] 2021-02-10 13:32
iPhone 11

**Comment by bbedward** [comment] 2021-02-10 14:25
I've been unable to reproduce so far after several tries, iOS 14.3 and 14.4 on iPhone XR.

I don't see anything in the deep link flow that would affect keychain data, I'd normally associate something like this with a corrupted KeyChain or storage.

There's some updates to the uni_links plugin upstream that are probably worth merging, though I'm not confident any of those changes would fix the issue.

What are your security settings? Is it set to lock the app with pin/biometrics on launch, with password? Maybe one of those is related.

**Comment by alecrios** [comment] 2021-02-10 14:40
@bbedward Ok, just reproduced again.

Authentication Method: Biometrics
Automatically Lock: Instantly
Wallet Password: On
Link: `nano:nano_3xk9wwjp89uod6gfwf775ctuibi4nybm4txi3gax3if1smun6hk57xxr6jnu?amount=1000000000000000000000000000000`

**Comment by bbedward** [comment] 2021-02-10 14:43
Thanks @alecrios 

I was able to reproduce, guessing it has something to do with the security settings. Will try to workout a fix for it.

**Comment by aufbakanleitung** [comment] 2021-02-10 15:28
So you say destroyed, but I assume the recovery sentence can still recover the wallet right?

**Comment by alecrios** [comment] 2021-02-10 15:31
Yeah, if you've backed up your wallet, you're fine. Doesn't affect your funds.

**Comment by bbedward** [comment] 2021-02-10 16:04
Fixed in d945a86996695e77e0d5b73d50731579d82b6b92

Specifically home_page.dart change

https://github.com/appditto/natrium_wallet_flutter/commit/d945a86996695e77e0d5b73d50731579d82b6b92#diff-268e07e62bef76704c9a0b4b0f3a9c67f06f9514d2d0fdf1f1b0cf6a94334e99R396

Going to push v2.3.7 to the stores with the fix, please re-open the issue if you experience it again after upgrading.

**Closed by bbedward** 2021-02-10 16:04 UTC
